---
- name: Deploy appication
  hosts: appnodes
  gather_facts: false
  become: true
  vars:
    color: ansiblue
    host_port: 8080
    container_port: 8080
    tag: suncavanaugh

  tasks:

  - name: Install podman
    ansible.builtin.package:
      name: podman
      state: present

  - name: Remove existing container if present
    containers.podman.podman_container:
      name: colors
      state: absent

  - name: Create the application container
    containers.podman.podman_container:
      name: colors
      image: quay.io/acme_corp/eda-app:{{ tag }}
      state: started
      recreate: true
      ports:
          - "{{ host_port }}:{{ container_port }}"
      env:
          APP_COLOR: "{{ color }}"
    register: container

  - name: Curl URL of application
    ansible.builtin.uri:
      url: "http://localhost:{{ host_port }}"
      return_content: yes
