---
- name: Deploy appication
  hosts: appnodes
  gather_facts: false
  become: true
  vars:
    host_port: 8080
    container_port: 8080
    # red, green, blue, darkblue, pink
    color: "green"
    tree: "trunk"
    
  tasks:
  
    - name: Create a color container
      containers.podman.podman_container:
        name: colors
        image: docker.io/mmumshad/simple-webapp-color:latest
        state: started
        network: host
        ports:
            - "{{ host_port }}:{{ container_port }}"
        env:
            APP_COLOR: "{{ color }}"
            tree: "{{ tree }}"
