---
- name: Webinar demo rulebook
  hosts: localhost
  sources:
    - name: listen for alerts
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5005
  rules:
    - name: App repo push event
      condition: event.payload.payload.repository.name == "eda-app"
      action:
        debug:

    - name: DEBUG
      condition: event.meta is defined
      action:
        run_job_template:
          name: "{{ job_template_name }}"
          organization: Default
