---
- name: Webinar demo rulebook
  hosts: localhost
  sources:
    - name: listen for alerts
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5005
  rules:
    - name: App repo push event
      condition: event.repository.full_name == "cloin/eda-app"
      action:
        debug:
